<h1><a href="#13-3-从-panic-中恢复-recover-" name="13-3-从-panic-中恢复-recover-"></a>13.3 从 panic 中恢复（Recover）</h1>
<p>正如名字一样，这个（recover）内建函数被用于从 panic 或 错误场景中恢复：让程序可以从 panicking 重新获得控制权，停止终止过程进而恢复正常执行。</p>
<p><code>recover</code> 只能在 defer 修饰的函数（参见 <a href="06.4.html">6.4 节</a>）中使用：用于取得 panic 调用中传递过来的错误值，如果是正常执行，调用 <code>recover</code> 会返回 nil，且没有其它效果。</p>
<p><u>总结</u>：panic 会导致栈被展开直到 defer 修饰的 recover() 被调用或者程序中止。</p>
<p>下面例子中的 protect 函数调用函数参数 g 来保护调用者防止从 g 中抛出的运行时 panic，并展示 panic 中的信息：</p>
<pre><code class="go">func protect(g func()) {
	defer func() {
		log.Println(&quot;done&quot;)
		// Println executes normally even if there is a panic
		if err := recover(); err != nil {
			log.Printf(&quot;run time panic: %v&quot;, err)
		}
	}()
	log.Println(&quot;start&quot;)
	g() //   possible runtime-error
}
</code></pre>
<p>这跟 Java 和 .NET 这样的语言中的 catch 块类似。</p>
<p>log 包实现了简单的日志功能：默认的 log 对象向标准错误输出中写入并打印每条日志信息的日期和时间。除了 <code>Println</code> 和 <code>Printf</code> 函数，其它的致命性函数都会在写完日志信息后调用 os.Exit(1)，那些退出函数也是如此。而 Panic 效果的函数会在写完日志信息后调用 panic；可以在程序必须中止或发生了临界错误时使用它们，就像当 web 服务器不能启动时那样（参见 <a href="15.4.html">15.4 节</a>中的例子）。</p>
<p>log 包用那些方法（methods）定义了一个 Logger 接口类型，如果你想自定义日志系统的话可以参考（参见 <a href="http://golang.org/pkg/log/#Logger">http://golang.org/pkg/log/#Logger</a>）。</p>
<p>这是一个展示 panic，defer 和 recover 怎么结合使用的完整例子：</p>
<p>示例 13.3 <a href="examples/chapter_13/panic_recover.go">panic_recover.go</a>：</p>
<pre><code class="go">// panic_recover.go
package main

import (
	&quot;fmt&quot;
)

func badCall() {
	panic(&quot;bad end&quot;)
}

func test() {
	defer func() {
		if e := recover(); e != nil {
			fmt.Printf(&quot;Panicing %s\r\n&quot;, e)
		}
	}()
	badCall()
	fmt.Printf(&quot;After bad call\r\n&quot;) // &lt;-- wordt niet bereikt
}

func main() {
	fmt.Printf(&quot;Calling test\r\n&quot;)
	test()
	fmt.Printf(&quot;Test completed\r\n&quot;)
}
</code></pre>
<p>输出：</p>
<pre><code>Calling test
Panicing bad end
Test completed
</code></pre>
<p><code>defer-panic-recover</code> 在某种意义上也是一种像 <code>if</code>，<code>for</code> 这样的控制流机制。</p>
<p>Go 标准库中许多地方都用了这个机制，例如，json 包中的解码和 regexp 包中的 Complie 函数。Go 库的原则是即使在包的内部使用了 panic，在它的对外接口（API）中也必须用 recover 处理成返回显式的错误。</p>
<h2><a href="#链接" name="链接"></a>链接</h2>
<ul>
  <li><a href="directory.html">目录</a></li>
  <li>上一节：<a href="13.2.html">错运行时异常和 panic</a></li>
  <li>下一节：<a href="13.4.html">自定义包中的错误处理和 panicking</a></li>
</ul>